import { toZone } from "../../src/helpers/index";

export const pivotModelData = function (xc: string) {
  return {
    version: 25,
    sheets: [
      {
        id: "pivot",
        name: "Pivot",
        colNumber: 26,
        rowNumber: 100,
        cells: {
          A1: "Created on",
          A2: "04/03/2024",
          A3: "03/03/2024",
          A4: "02/02/2024",
          A5: "04/02/2024",
          A6: "03/28/2024",
          A7: "04/02/2024",
          A8: "04/02/2024",
          A9: "02/27/2024",
          A10: "04/01/2024",
          A11: "04/02/2024",
          A12: "04/03/2024",
          A13: "02/03/2024",
          A14: "03/03/2024",
          A15: "01/26/2024",
          A16: "03/27/2024",
          A17: "03/27/2024",
          A18: "03/31/2024",
          A19: "01/31/2024",
          A20: "04/02/2024",
          A21: "04/05/2024",
          A22: "05/19/2024",
          B1: "Opportunity",
          B2: "my opportunity",
          B3: "test opportunity",
          B4: "interested in tables",
          B5: "Interest in your products",
          B6: "Open Space Design",
          B7: "Modern Open Space",
          B8: "Office Design and Architecture",
          B9: "Distributor Contract",
          B10: "Furnitures",
          B11: "Office Design Project",
          B12: "abc opportunity",
          B13: "Quote for 600 Chairs",
          B14: "Devis pour 150 tapis",
          B15: "5 VP Chairs",
          B16: "Customizable Desk",
          B17: "DeltaPC: 10 Computer Desks",
          B18: "Potential Distributor",
          B19: "Info about services",
          B20: "Quote for 12 Tables",
          B21: "Need 20 Desks",
          B22: "Access to Online Catalog",
          C1: "Contact Name",
          C2: "Michel",
          C4: "Alice",
          C7: "Bob",
          C9: "Charlie",
          C10: "Robin",
          C13: "Erik",
          C14: "Erik",
          C15: "Carlos",
          C16: "Charles",
          C17: "Roger",
          C18: "Mich-Mich",
          C20: "Will",
          D1: "Email",
          D2: "admin@yourcompany.example.com",
          D3: "info@yourcompany.example.com",
          D4: "adam@example.com",
          D5: "info@example.com",
          D6: "info@example.com",
          D7: "henry@exemple.com",
          D8: "info@my.example.com",
          D9: "john@tech.info",
          D10: "info@my.example.com",
          D11: "info@exemple.com",
          D12: "info@yourcompany.example.com",
          D13: "erik@blop.com",
          D14: "erik@blop.com",
          D15: "info@yourcompany.example.com",
          D16: "info@yourcompany.example.com",
          D17: "info@my.example.com",
          D18: "Carlos@inc.sa",
          D19: "info@mycompany.com",
          D20: "Will@example.com",
          D21: "info@mycompany.net",
          D22: "mich-mich@example.com",
          E1: "Salesperson",
          E2: "Kevin",
          E3: "Kevin",
          E4: "Kevin",
          E5: "Eden",
          E6: "Eden",
          E7: "Kevin",
          E8: "Kevin",
          E9: "Kevin",
          E10: "Kevin",
          E11: "Eden",
          E12: "Kevin",
          E13: "Kevin",
          E14: "Kevin",
          E15: "Kevin",
          E16: "Eden",
          E17: "Eden",
          E18: "Eden",
          E19: "Kevin",
          E20: "Kevin",
          E21: "Kevin",
          E22: "Eden",
          F1: "Expected Revenue",
          F2: "2000",
          F3: "11000",
          F4: "4500",
          F8: "9000",
          F9: "19800",
          F10: "3800",
          F11: "24000",
          F13: "22500",
          F14: "40000",
          F15: "5600",
          F16: "15000",
          F17: "35000",
          F18: "1000",
          F19: "25000",
          F20: "40000",
          F21: "60000",
          F22: "2000",
          G1: "Expected MRR",
          G7: "333.33",
          H1: "Stage",
          H2: "New",
          H3: "New",
          H4: "New",
          H5: "Won",
          H6: "Proposition",
          H7: "Won",
          H8: "Proposition",
          H9: "Won",
          H10: "Qualified",
          H11: "New",
          H12: "New",
          H13: "Qualified",
          H14: "New",
          H15: "Proposition",
          H16: "Proposition",
          H17: "Qualified",
          H18: "Qualified",
          H19: "Qualified",
          H20: "New",
          H21: "Proposition",
          H22: "Won",
          I1: "Active",
          I2: "TRUE",
          I3: "FALSE",
          I4: "TRUE",
          I5: "TRUE",
          I6: "TRUE",
          I7: "TRUE",
          I8: "TRUE",
          I9: "TRUE",
          I10: "TRUE",
          I11: "TRUE",
          I12: "FALSE",
          I13: "FALSE",
          I14: "FALSE",
          I15: "FALSE",
          I16: "FALSE",
          I17: "FALSE",
          I18: "FALSE",
          I19: "FALSE",
          I20: "FALSE",
          I21: "FALSE",
          I22: "FALSE",
        },
        styles: {},
        formats: {
          "A2:A22": 2,
          "F2:F22": 1,
        },
        isVisible: true,
        areGridLinesVisible: true,
      },
    ],
    formats: {
      "1": "[$$]#,##0.00",
      "2": "mm/dd/yyyy",
    },
    borders: {},
    revisionId: "fbf5c369-70ff-4a05-929e-859e0608c53a",
    uniqueFigureIds: true,
    settings: {
      locale: {
        name: "English (US)",
        code: "en_US",
        thousandsSeparator: ",",
        decimalSeparator: ".",
        weekStart: 7,
        dateFormat: "m/d/yyyy",
        timeFormat: "hh:mm:ss a",
        formulaArgSeparator: ",",
      },
    },
    pivots: {
      "1": {
        type: "SPREADSHEET",
        columns: [
          {
            fieldName: "Expected Revenue",
          },
        ],
        rows: [],
        measures: [
          {
            id: "__count:sum",
            fieldName: "__count",
            aggregator: "sum",
          },
        ],
        name: "My pivot",
        dataSet: {
          zone: toZone(xc),
          sheetId: "pivot",
        },
        formulaId: "1",
      },
    },
    pivotNextId: 2,
    customTableStyles: {},
  };
};
