export const currenciesData = [
  { decimalPlaces: 2, name: "Afghan afghani", code: "AFN", symbol: "Afs", position: "after" },
  { decimalPlaces: 2, name: "Albanian lek", code: "ALL", symbol: "L", position: "after" },
  { decimalPlaces: 2, name: "Algerian dinar", code: "DZD", symbol: "DA", position: "after" },
  { decimalPlaces: 2, name: "Angolan kwanza", code: "AOA", symbol: "Kz", position: "after" },
  { decimalPlaces: 2, name: "Argentine peso", code: "ARS", symbol: "$", position: "after" },
  { decimalPlaces: 2, name: "Armenian dram", code: "AMD", symbol: "դր.", position: "after" },
  { decimalPlaces: 1, name: "Aruban florin", code: "AWG", symbol: "Afl.", position: "after" },
  { decimalPlaces: 2, name: "Australian dollar", code: "AUD", symbol: "$", position: "after" },
  { decimalPlaces: 2, name: "Azerbaijani manat", code: "AZN", symbol: "m", position: "after" },
  { decimalPlaces: 2, name: "Bahamian dollar", code: "BSD", symbol: "B$", position: "after" },
  { decimalPlaces: 2, name: "Bahraini dinar", code: "BHD", symbol: "BD", position: "after" },
  { decimalPlaces: 2, name: "Bangladeshi taka", code: "BDT", symbol: "৳", position: "after" },
  { decimalPlaces: 5, name: "Barbados dollar", code: "BBD", symbol: "Bds$", position: "after" },
  { decimalPlaces: 2, name: "Belarusian ruble", code: "BYN", symbol: "Br", position: "after" },
  { decimalPlaces: 2, name: "Belarusian ruble", code: "BYR", symbol: "BR", position: "after" },
  { decimalPlaces: 2, name: "Belize dollar", code: "BZD", symbol: "BZ$", position: "after" },
  { decimalPlaces: 1, name: "Bermudian dollar", code: "BMD", symbol: "BD$", position: "after" },
  { decimalPlaces: 2, name: "Bhutanese ngultrum", code: "BTN", symbol: "Nu.", position: "after" },
  { decimalPlaces: 2, name: "Boliviano", code: "BOB", symbol: "Bs.", position: "after" },
  {
    decimalPlaces: 2,
    name: "Bosnia and Herzegovina convertible mark",
    code: "BAM",
    symbol: "KM",
    position: "after",
  },
  { decimalPlaces: 0, name: "Botswana pula", code: "BWP", symbol: "P", position: "after" },
  { decimalPlaces: 2, name: "Brazilian real", code: "BRL", symbol: "R$", position: "after" },
  { decimalPlaces: 2, name: "Brunei dollar", code: "BND", symbol: "$", position: "after" },
  { decimalPlaces: 2, name: "Bulgarian lev", code: "BGN", symbol: "лв", position: "after" },
  { decimalPlaces: 2, name: "Burundian franc", code: "BIF", symbol: "FBu", position: "after" },
  { decimalPlaces: 2, name: "Cambodian riel", code: "KHR", symbol: "៛", position: "after" },
  { decimalPlaces: 2, name: "Canadian dollar", code: "CAD", symbol: "$", position: "after" },
  { decimalPlaces: 4, name: "Cape Verdean escudo", code: "CVE", symbol: "$", position: "after" },
  { decimalPlaces: 3, name: "Chilean peso", code: "CLP", symbol: "$", position: "after" },
  { decimalPlaces: 2, name: "Chinese yuan", code: "CNY", symbol: "¥", position: "after" },
  { decimalPlaces: 2, name: "Colombian peso", code: "COP", symbol: "$", position: "after" },
  { decimalPlaces: 3, name: "Comorian franc", code: "KMF", symbol: "CF", position: "after" },
  { decimalPlaces: 2, name: "Congolese franc", code: "CDF", symbol: "Fr", position: "after" },
  { decimalPlaces: 2, name: "Costa Rican colón", code: "CRC", symbol: "₡", position: "after" },
  { decimalPlaces: 2, name: "Croatian kuna", code: "HRK", symbol: "kn", position: "after" },
  { decimalPlaces: 2, name: "Cuban convertible peso", code: "CUC", symbol: "$", position: "after" },
  { decimalPlaces: 2, name: "Cuban peso", code: "CUP", symbol: "$", position: "after" },
  { decimalPlaces: 2, name: "Czech koruna", code: "CZK", symbol: "Kč", position: "after" },
  { decimalPlaces: 5, name: "Danish krone", code: "DKK", symbol: "kr", position: "after" },
  { decimalPlaces: 2, name: "Djiboutian franc", code: "DJF", symbol: "Fdj", position: "after" },
  { decimalPlaces: 2, name: "Dominican peso", code: "DOP", symbol: "RD$", position: "after" },
  { decimalPlaces: 2, name: "Egyptian pound", code: "EGP", symbol: "E£", position: "after" },
  { decimalPlaces: 3, name: "Eritrean nakfa", code: "ERN", symbol: "Nfk", position: "after" },
  { decimalPlaces: 2, name: "Ethiopian birr", code: "ETB", symbol: "Br", position: "after" },
  { decimalPlaces: 2, name: "Euro", code: "EUR", symbol: "€", position: "after" },
  { decimalPlaces: 2, name: "Falkland Islands pound", code: "FKP", symbol: "£", position: "after" },
  { decimalPlaces: 2, name: "Fiji dollar", code: "FJD", symbol: "FJ$", position: "after" },
  { decimalPlaces: 2, name: "Gambian dalasi", code: "GMD", symbol: "D", position: "after" },
  { decimalPlaces: 2, name: "Georgian lari", code: "GEL", symbol: "ლ", position: "after" },
  { decimalPlaces: 2, name: "Ghanaian cedi", code: "GHS", symbol: "GH¢", position: "after" },
  { decimalPlaces: 1, name: "Gibraltar pound", code: "GIP", symbol: "£", position: "after" },
  { decimalPlaces: 2, name: "Guatemalan Quetzal", code: "GTQ", symbol: "Q", position: "after" },
  { decimalPlaces: 2, name: "Guinean franc", code: "GNF", symbol: "FG", position: "after" },
  { decimalPlaces: 1, name: "Guyanese dollar", code: "GYD", symbol: "$", position: "after" },
  { decimalPlaces: 2, name: "Haitian gourde", code: "HTG", symbol: "G", position: "after" },
  { decimalPlaces: 2, name: "Honduran lempira", code: "HNL", symbol: "L", position: "after" },
  { decimalPlaces: 1, name: "Hong Kong dollar", code: "HKD", symbol: "$", position: "after" },
  { decimalPlaces: 2, name: "Hungarian forint", code: "HUF", symbol: "Ft", position: "after" },
  { decimalPlaces: 2, name: "Icelandic króna", code: "ISK", symbol: "kr", position: "after" },
  { decimalPlaces: 1, name: "Indian rupee", code: "INR", symbol: "₹", position: "after" },
  { decimalPlaces: 2, name: "Indonesian rupiah", code: "IDR", symbol: "Rp", position: "after" },
  { decimalPlaces: 2, name: "Iranian rial", code: "IRR", symbol: "﷼", position: "after" },
  { decimalPlaces: 2, name: "Iraqi dinar", code: "IQD", symbol: "ع.د", position: "after" },
  { decimalPlaces: 2, name: "Israeli new shekel", code: "ILS", symbol: "₪", position: "before" },
  { decimalPlaces: 1, name: "Jamaican dollar", code: "JMD", symbol: "$", position: "after" },
  { decimalPlaces: 2, name: "Japanese yen", code: "JPY", symbol: "¥", position: "after" },
  { decimalPlaces: 2, name: "Jordanian dinar", code: "JOD", symbol: "د.ا", position: "after" },
  { decimalPlaces: 2, name: "Kenyan shilling", code: "KES", symbol: "KSh", position: "after" },
  { decimalPlaces: 2, name: "Kuwaiti dinar", code: "KWD", symbol: "د.ك", position: "after" },
  { decimalPlaces: 1, name: "Kyrgyzstani som", code: "KGS", symbol: "лв", position: "after" },
  {
    decimalPlaces: 2,
    name: "Netherlands Antillean guilder",
    code: "ANG",
    symbol: "ƒ",
    position: "after",
  },
  { decimalPlaces: 2, name: "North Korean won", code: "KPW", symbol: "₩", position: "after" },
  { decimalPlaces: 2, name: "Pound sterling", code: "GBP", symbol: "£", position: "after" },
  { decimalPlaces: 1, name: "South Korean won", code: "KRW", symbol: "₩", position: "after" },
  { decimalPlaces: 2, name: "Swedish krona", code: "SEK", symbol: "kr", position: "after" },
  { decimalPlaces: 2, name: "Swiss franc", code: "CHF", symbol: "CHF", position: "after" },
  { decimalPlaces: 2, name: "Unidad de Fomento", code: "CLF", symbol: "$", position: "after" },
  { decimalPlaces: 2, name: "Unidad de Valor Real", code: "COU", symbol: "$", position: "after" },
  {
    decimalPlaces: 1,
    name: "United Arab Emirates dirham",
    code: "AED",
    symbol: "د.إ",
    position: "after",
  },
  { decimalPlaces: 2, name: "United States dollar", code: "USD", symbol: "$", position: "before" },
];
