import { Command } from "../../src";

export const commands: Command[] = [
  { sheetId: "Sheet1", col: 1, row: 3, content: "4", type: "UPDATE_CELL" },
  { sheetId: "Sheet1", col: 1, row: 4, content: "4", type: "UPDATE_CELL" },
  { sheetId: "Sheet1", col: 1, row: 5, content: "4", type: "UPDATE_CELL" },
  { sheetId: "Sheet1", col: 1, row: 6, content: "=B6", type: "UPDATE_CELL" },
  { sheetId: "Sheet1", target: [{ left: 1, right: 1, top: 6, bottom: 6 }], type: "DELETE_CONTENT" },
  {
    sheetId: "Sheet1",
    target: [{ left: 1, right: 1, top: 4, bottom: 4 }],
    type: "CLEAR_FORMATTING",
  },
  { sheetId: "Sheet1", target: [{ left: 1, right: 1, top: 3, bottom: 5 }], type: "DELETE_CONTENT" },
  { sheetId: "Sheet1", col: 0, row: 4, content: "4", type: "UPDATE_CELL" },
  {
    sheetId: "Sheet1",
    position: "before",
    dimension: "COL",
    base: 1,
    quantity: 1,
    type: "ADD_COLUMNS_ROWS",
  },
  {
    sheetId: "Sheet1",
    position: "after",
    dimension: "COL",
    base: 2,
    quantity: 1,
    type: "ADD_COLUMNS_ROWS",
  },
  { dimension: "COL", sheetId: "Sheet1", elements: [2], size: 132, type: "RESIZE_COLUMNS_ROWS" },
  { dimension: "ROW", sheetId: "Sheet1", elements: [2], size: 61, type: "RESIZE_COLUMNS_ROWS" },
  {
    sheetId: "Sheet1",
    position: "before",
    base: 5,
    quantity: 1,
    dimension: "ROW",
    type: "ADD_COLUMNS_ROWS",
  },
  {
    sheetId: "Sheet1",
    position: "after",
    base: 11,
    quantity: 1,
    dimension: "ROW",
    type: "ADD_COLUMNS_ROWS",
  },
  { sheetId: "Sheet1", areGridLinesVisible: false, type: "SET_GRID_LINES_VISIBILITY" },
  { sheetId: "Sheet1", areGridLinesVisible: true, type: "SET_GRID_LINES_VISIBILITY" },
  { sheetId: "Sheet1", dimension: "COL", elements: [2, 3], type: "HIDE_COLUMNS_ROWS" },
  { sheetId: "Sheet1", dimension: "COL", elements: [5, 6, 8, 9], type: "HIDE_COLUMNS_ROWS" },
  { sheetId: "Sheet1", elements: [8, 9], dimension: "COL", type: "UNHIDE_COLUMNS_ROWS" },
  { sheetId: "Sheet1", elements: [5, 6], dimension: "COL", type: "UNHIDE_COLUMNS_ROWS" },
  { sheetId: "Sheet1", elements: [2, 3], dimension: "COL", type: "UNHIDE_COLUMNS_ROWS" },
  { sheetId: "Sheet1", quantity: 6, type: "FREEZE_ROWS" },
  { sheetId: "Sheet1", quantity: 2, type: "FREEZE_COLUMNS" },
  { sheetId: "Sheet1", type: "UNFREEZE_COLUMNS_ROWS" },
  { sheetId: "Sheet1", target: [{ left: 2, right: 2, top: 4, bottom: 6 }], type: "ADD_MERGE" },
  { sheetId: "Sheet1", target: [{ left: 4, right: 5, top: 9, bottom: 11 }], type: "ADD_MERGE" },
  {
    sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136",
    position: 1,
    name: "Sheet2",
    type: "CREATE_SHEET",
  },
  { sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136", name: "new name", type: "RENAME_SHEET" },
  { sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136", color: "#FFD966", type: "COLOR_SHEET" },
  { sheetId: "Sheet1", color: "#D9EAD3", type: "COLOR_SHEET" },
  { sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136", delta: -1, type: "MOVE_SHEET" },
  { sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136", delta: 1, type: "MOVE_SHEET" },
  {
    sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136",
    sheetIdTo: "5c555a62-a750-4877-97ac-654f3b85e287",
    type: "DUPLICATE_SHEET",
  },
  { sheetId: "5c555a62-a750-4877-97ac-654f3b85e287", type: "DELETE_SHEET" },
  {
    sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136",
    col: 2,
    row: 14,
    content: "4",
    type: "UPDATE_CELL",
  },
  {
    sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136",
    col: 2,
    row: 15,
    content: "4",
    type: "UPDATE_CELL",
  },
  {
    sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136",
    col: 2,
    row: 16,
    content: "4",
    type: "UPDATE_CELL",
  },
  {
    sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136",
    col: 2,
    row: 17,
    content: "4",
    type: "UPDATE_CELL",
  },
  {
    sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136",
    col: 2,
    row: 18,
    content: "7",
    type: "UPDATE_CELL",
  },
  {
    sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136",
    col: 2,
    row: 19,
    content: "7",
    type: "UPDATE_CELL",
  },
  { sheetId: "Sheet1", type: "DELETE_SHEET" },
  {
    sheetId: "c1c76aab-fd51-45af-a7f0-70d6bb338888",
    position: 1,
    name: "Sheet1",
    type: "CREATE_SHEET",
  },
  { sheetId: "57047cd7-c980-4231-b9f2-1da2a98a3136", type: "HIDE_SHEET" },
  {
    sheetId: "Sheet1",
    ranges: [{ _sheetId: "Sheet1", _zone: { left: 2, right: 3, top: 10, bottom: 15 } }],
    cf: {
      id: "e548ae9c-3109-4c7f-a493-1da693c1c3c3",
      rule: {
        type: "CellIsRule",
        operator: "IsNotEmpty",
        style: { fillColor: "#b6d7a8" },
        values: [],
      },
    },
    type: "ADD_CONDITIONAL_FORMAT",
  },
  {
    cf: {
      rule: {
        type: "CellIsRule",
        operator: "BeginsWith",
        style: { fillColor: "#b6d7a8" },
        values: ["=$A$5"],
      },
      id: "e548ae9c-3109-4c7f-a493-1da693c1c3c3",
    },
    ranges: [{ _zone: { top: 10, left: 2, bottom: 15, right: 3 }, _sheetId: "Sheet1" }],
    sheetId: "Sheet1",
    type: "ADD_CONDITIONAL_FORMAT",
  },
  {
    sheetId: "Sheet1",
    ranges: [{ _sheetId: "Sheet1", _zone: { left: 2, right: 3, top: 10, bottom: 15 } }],
    cf: {
      id: "f340f1a6-6c7c-40a5-932c-790fe6344227",
      rule: {
        type: "CellIsRule",
        operator: "IsNotEmpty",
        style: { fillColor: "#b6d7a8" },
        values: [],
      },
    },
    type: "ADD_CONDITIONAL_FORMAT",
  },
  {
    cfId: "f340f1a6-6c7c-40a5-932c-790fe6344227",
    delta: 1,
    sheetId: "Sheet1",
    type: "CHANGE_CONDITIONAL_FORMAT_PRIORITY",
  },
  {
    id: "f340f1a6-6c7c-40a5-932c-790fe6344227",
    sheetId: "Sheet1",
    type: "REMOVE_CONDITIONAL_FORMAT",
  },
  {
    id: "e548ae9c-3109-4c7f-a493-1da693c1c3c3",
    sheetId: "Sheet1",
    type: "REMOVE_CONDITIONAL_FORMAT",
  },
  {
    sheetId: "Sheet1",
    target: [{ left: 2, right: 2, top: 10, bottom: 12 }],
    border: { position: "all", color: "#000000", style: "thin" },
    type: "SET_ZONE_BORDERS",
  },
  {
    sheetId: "Sheet1",
    target: [{ left: 2, right: 2, top: 13, bottom: 15 }],
    style: { fillColor: "#FF9900" },
    type: "SET_FORMATTING",
  },
  {
    sheetId: "Sheet1",
    target: [{ left: 0, right: 0, top: 4, bottom: 4 }],
    style: { bold: true },
    type: "SET_FORMATTING",
  },
  { sheetId: "Sheet1", target: [], format: "", type: "SET_FORMATTING" },
  {
    sheetId: "Sheet1",
    target: [{ left: 0, right: 0, top: 4, bottom: 4 }],
    format: "0.00%",
    type: "SET_FORMATTING",
  },
  {
    ranges: [{ _sheetId: "Sheet1", _zone: { left: 1, right: 2, top: 18, bottom: 20 } }],
    sheetId: "Sheet1",
    config: {
      hasFilters: false,
      totalRow: false,
      firstColumn: false,
      lastColumn: false,
      numberOfHeaders: 1,
      bandedRows: true,
      bandedColumns: false,
      automaticAutofill: true,
      styleId: "TableStyleMedium1",
    },
    tableType: "static",
    type: "CREATE_TABLE",
  },
  {
    sheetId: "Sheet1",
    zone: { top: 18, left: 1, bottom: 20, right: 2 },
    config: { hasFilters: true },
    type: "UPDATE_TABLE",
  },
  {
    tableStyleId: "d0dfeb18-6986-4bb1-965f-40c78cd4b1a4",
    tableStyleName: "Custom Table Style",
    templateName: "mediumBandedBorders",
    primaryColor: "#E69138",
    type: "CREATE_TABLE_STYLE",
  },
  {
    sheetId: "Sheet1",
    zone: { top: 18, left: 1, bottom: 20, right: 2 },
    config: { styleId: "d0dfeb18-6986-4bb1-965f-40c78cd4b1a4" },
    type: "UPDATE_TABLE",
  },
  {
    sheetId: "Sheet1",
    zone: { top: 18, left: 1, bottom: 20, right: 2 },
    config: { styleId: "d0dfeb18-6986-4bb1-965f-40c78cd4b1a4" },
    type: "UPDATE_TABLE",
  },
  { tableStyleId: "d0dfeb18-6986-4bb1-965f-40c78cd4b1a4", type: "REMOVE_TABLE_STYLE" },
  { sheetId: "Sheet1", target: [{ top: 18, left: 1, bottom: 20, right: 2 }], type: "REMOVE_TABLE" },
  { sheetId: "Sheet1", dimension: "COL", start: 3, end: 5, type: "GROUP_HEADERS" },
  { sheetId: "Sheet1", dimension: "COL", start: 3, end: 4, type: "GROUP_HEADERS" },
  { sheetId: "Sheet1", dimension: "COL", start: 3, end: 4, type: "FOLD_HEADER_GROUP" },
  { sheetId: "Sheet1", dimension: "COL", start: 3, end: 5, type: "FOLD_HEADER_GROUP" },
  { sheetId: "Sheet1", dimension: "COL", start: 3, end: 4, type: "UNFOLD_HEADER_GROUP" },
  { sheetId: "Sheet1", dimension: "ROW", start: 5, end: 8, type: "GROUP_HEADERS" },
  { sheetId: "Sheet1", dimension: "ROW", start: 6, end: 8, type: "GROUP_HEADERS" },
  { sheetId: "Sheet1", dimension: "ROW", start: 6, end: 8, type: "UNGROUP_HEADERS" },
  { sheetId: "Sheet1", dimension: "ROW", start: 5, end: 5, type: "UNGROUP_HEADERS" },
  { sheetId: "Sheet1", dimension: "ROW", start: 6, end: 8, type: "FOLD_HEADER_GROUP" },
  { sheetId: "Sheet1", dimension: "ROW", type: "UNFOLD_ALL_HEADER_GROUPS" },
  { sheetId: "Sheet1", dimension: "ROW", start: 6, end: 8, type: "FOLD_HEADER_GROUP" },
  { sheetId: "Sheet1", dimension: "ROW", start: 6, end: 8, type: "UNGROUP_HEADERS" },
  { sheetId: "Sheet1", dimension: "COL", start: 2, end: 3, type: "UNGROUP_HEADERS" },
  { sheetId: "Sheet1", dimension: "COL", start: 3, end: 4, type: "UNGROUP_HEADERS" },
  { sheetId: "Sheet1", dimension: "COL", start: 3, end: 5, type: "UNGROUP_HEADERS" },
  {
    ranges: [{ _sheetId: "Sheet1", _zone: { left: 6, right: 6, top: 3, bottom: 7 } }],
    sheetId: "Sheet1",
    rule: {
      id: "8342c8e6-7feb-4f50-b1ef-4d8288890917",
      criterion: { type: "isBoolean", values: [] },
    },
    type: "ADD_DATA_VALIDATION_RULE",
  },
  { col: 6, row: 3, sheetId: "Sheet1", content: "FALSE", type: "UPDATE_CELL" },
  { col: 6, row: 4, sheetId: "Sheet1", content: "FALSE", type: "UPDATE_CELL" },
  { col: 6, row: 5, sheetId: "Sheet1", content: "FALSE", type: "UPDATE_CELL" },
  { col: 6, row: 6, sheetId: "Sheet1", content: "FALSE", type: "UPDATE_CELL" },
  { col: 6, row: 7, sheetId: "Sheet1", content: "FALSE", type: "UPDATE_CELL" },
  {
    ranges: [{ _sheetId: "Sheet1", _zone: { left: 6, right: 6, top: 3, bottom: 7 } }],
    sheetId: "Sheet1",
    rule: {
      id: "e860d4a8-477d-465f-ad74-0b45d370c0d6",
      criterion: { type: "isValueInList", values: [], displayStyle: "arrow" },
    },
    type: "ADD_DATA_VALIDATION_RULE",
  },
  {
    sheetId: "Sheet1",
    ranges: [{ _zone: { top: 3, left: 6, bottom: 7, right: 6 }, _sheetId: "Sheet1" }],
    rule: {
      id: "e860d4a8-477d-465f-ad74-0b45d370c0d6",
      criterion: { type: "isValueInList", values: [], displayStyle: "arrow" },
    },
    type: "ADD_DATA_VALIDATION_RULE",
  },
  {
    sheetId: "Sheet1",
    id: "e860d4a8-477d-465f-ad74-0b45d370c0d6",
    type: "REMOVE_DATA_VALIDATION_RULE",
  },
  {
    pivotId: "4277f7bf-dd74-4ebb-85b8-9dee21b261c5",
    pivot: {
      dataSet: { zone: { left: 6, right: 6, top: 3, bottom: 7 }, sheetId: "Sheet1" },
      columns: [],
      rows: [],
      measures: [],
      name: "New pivot",
      type: "SPREADSHEET",
    },
    type: "ADD_PIVOT",
  },
  {
    sheetId: "5d17252a-7b7a-448e-9c9b-706349d797cb",
    name: "Pivot #1",
    position: 1,
    type: "CREATE_SHEET",
  },
  {
    sheetId: "5d17252a-7b7a-448e-9c9b-706349d797cb",
    col: 0,
    row: 0,
    content: "=PIVOT(1)",
    type: "UPDATE_CELL",
  },
  {
    tableType: "dynamic",
    sheetId: "5d17252a-7b7a-448e-9c9b-706349d797cb",
    ranges: [
      {
        _sheetId: "5d17252a-7b7a-448e-9c9b-706349d797cb",
        _zone: { left: 0, right: 0, top: 0, bottom: 0 },
      },
    ],
    config: {
      hasFilters: false,
      totalRow: false,
      firstColumn: true,
      lastColumn: false,
      numberOfHeaders: 1,
      bandedRows: true,
      bandedColumns: false,
      styleId: "TableStyleMedium5",
      automaticAutofill: false,
    },
    type: "CREATE_TABLE",
  },
  {
    pivotId: "4277f7bf-dd74-4ebb-85b8-9dee21b261c5",
    pivot: {
      dataSet: { zone: { left: 6, right: 6, top: 3, bottom: 7 }, sheetId: "Sheet1" },
      columns: [{ fieldName: "false", order: "asc" }],
      rows: [],
      measures: [],
      name: "New pivot",
      type: "SPREADSHEET",
    },
    type: "UPDATE_PIVOT",
  },
  {
    pivotId: "4277f7bf-dd74-4ebb-85b8-9dee21b261c5",
    newPivotId: "306c16f6-41f4-4693-9a3c-d0db948043d9",
    duplicatedPivotName: "New pivot (copy)",
    type: "DUPLICATE_PIVOT",
  },
  {
    sheetId: "51c50ed8-ba75-406e-ab4d-a0cdfed42714",
    name: "New pivot (copy) (Pivot #2)",
    position: 2,
    type: "CREATE_SHEET",
  },
  {
    sheetId: "51c50ed8-ba75-406e-ab4d-a0cdfed42714",
    col: 0,
    row: 0,
    content: "=PIVOT(2)",
    type: "UPDATE_CELL",
  },
  {
    tableType: "dynamic",
    sheetId: "51c50ed8-ba75-406e-ab4d-a0cdfed42714",
    ranges: [
      {
        _sheetId: "51c50ed8-ba75-406e-ab4d-a0cdfed42714",
        _zone: { left: 0, right: 0, top: 0, bottom: 0 },
      },
    ],
    config: {
      hasFilters: false,
      totalRow: false,
      firstColumn: true,
      lastColumn: false,
      numberOfHeaders: 1,
      bandedRows: true,
      bandedColumns: false,
      styleId: "TableStyleMedium5",
      automaticAutofill: false,
    },
    type: "CREATE_TABLE",
  },
  { pivotId: "306c16f6-41f4-4693-9a3c-d0db948043d9", type: "REMOVE_PIVOT" },
];
