#!/bin/sh

# Husky Env Variables :
# HUSKY_PRE_COMMIT : if set to 0, disable pre-commit hook
# HUSKY_INPUT_ENV: if set to 0, disable the possibility of user input for the hook

npx="npx"

# For Windows
if [ "$OSTYPE" = "msys" ]; then
    export PATH="/usr/bin:/usr/local/bin:$PATH"
    npx="npx.cmd"
fi
. "$(dirname "$0")/_/husky.sh"

if [ "$HUSKY_PRE_COMMIT" != 0 ]; then
    $npx lint-staged

    consoleregexp='console\.|debugger'
    if test $(git diff --cached | grep -nE $consoleregexp | wc -l) != 0
    then
        if [ "$HUSKY_INPUT_ENV" != 0 ] && [ "$OSTYPE" != "msys" ]; then
            # activate user inputs
            exec < /dev/tty
            exec git diff --cached --color | grep -nE $consoleregexp -A 2 -B 2
            read -p "There are some occurrences of forbidden patterns at your modification. Are you sure want to continue? (y/n)" yn
            echo $yn | grep ^[Yy]$
            if [ $? -ne 0 ]; then
                exit 1; # THE USER DONT WANT TO CONTINUE SO ROLLBACK
            fi
        else
            echo -e "\033[1;31mWARNING: Some occurences of forbidden patterns were detected \033[0m"
            exec git diff --cached --color | grep -nE $consoleregexp -A 2 -B 2
        fi
    fi

    # Css wrap check
    scssregexp='.*\.scss'
    ignoreFileInstruction='\/\* husky-ignore \*\/'
    filelist=()
    for file in $(git diff --cached --name-only | grep -E $scssregexp); do
        # The script is run in -e mode (see husky.sh:23)
        # and if grep does not match, it raises an error
        # Therefore, we need to use || true to avoid the script to stop
        match=$(echo "$(head -n1 $file)" | grep -E "^\s*\.o-spreadsheet|$ignoreFileInstruction" || true)
        if [ -z "$match" ]; then
            filelist+=($file)
        fi
    done

    if [ ${#filelist[@]} -ne 0 ]; then
        echo "Some scss files are not scoped to .o-spreadsheet:"
        printf "\t%s\n" "- ${filelist[@]}"
        cat <<-EOF

Your file should start with:
.o-spreadsheet {
    ...
}
and the selector should encompass all the style.
EOF
        exit 1
    fi
fi
