name: Release Workflow

on:
  push:
    # Match LTS, saas releases >= 10 and master
    branches: ["[1-9][0-9].[0-9]", "saas-[1-9][0-9].[0-9]", "master"]

jobs:
  build:
    if: contains(github.event.head_commit.message, '[REL]')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse.outputs.version }}
      body: ${{ steps.parse.outputs.body }}
      prerelease: ${{ steps.parse.outputs.prerelease }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Parse
        id: parse
        run: |
          npm i @actions/core@3.0.0 @actions/github@9.0.0 --no-save && \
          node tools/parse_message.mjs

      - name: Build
        run: npm ci && npm run dist

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ needs.build.outputs.version }}
          body: ${{ needs.build.outputs.body }}
          artifacts: "./dist/*.*"
          makeLatest: false
          prerelease: ${{ needs.build.outputs.prerelease }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
